<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:servicio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:servicio">
<types>
<xsd:schema targetNamespace="urn:servicio">
<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>
</xsd:schema>
</types>
<message name="traerRequest">
<part name="id" type="xsd:string"/>
</message>
<message name="traerResponse">
<part name="return" type="xsd:string"/>
</message>
<portType name="servicioPortType">
<operation name="traer">
<input message="tns:traerRequest"/>
<output message="tns:traerResponse"/>
</operation>
</portType>
<binding name="servicioBinding" type="tns:servicioPortType">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="traer">
<soap:operation soapAction="http://localhost/phpProyecto/webService/webservice.php/traer" style="rpc"/>
<input>
<soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</input>
<output>
<soap:body use="encoded" namespace="" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</output>
</operation>
</binding>
<service name="servicio">
<port name="servicioPort" binding="tns:servicioBinding">
<soap:address location="http://localhost/phpProyecto/webService/webservice.php"/>
</port>
</service>
</definitions>